r"""Write the LaTeX tables of the revised manuscript from the analysis outputs.

Every number in these tables is read from a result file, not typed by hand:
  revision/statistics/system_metrics_with_cis.csv, mcnemar_rule_vs_17.csv, alignment_delta.csv
  revision/supervised_grouped/supervised_grouped_metrics.csv
  revision/prompt_ablation/ablation_metrics_full_precision.csv
  revision/label_audit/sample_manifest.csv, disagreement_cases.csv
  all_predictions_3class.csv, code/output/3class_eval/phase_a/hrsf/hrsf_predictions_at_best_alpha.csv

Output: revision/overleaf/tables/*.tex (\input by the manuscript), and the
supplementary CSV files in revision/overleaf_supplementary/.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REV = HERE.parent
ROOT = REV.parent
CODE = ROOT / "code" if (ROOT / "code" / "output").is_dir() else ROOT  # project layout or repository layout
OUT = REV / "overleaf" / "tables"
SUPP = REV / "overleaf_supplementary"
LABELS = ["focused", "mix", "others"]
ORDER = ["Rule-based", "Qwen2.5-72B", "Yi-1.5-9B", "Mistral-7B", "Phi-4-mini", "Llama-3.1-8B", "Random Forest",
         "qwen-7b", "Qwen2.5-7B", "XGBoost", "LightGBM", "Logistic Regression", "Linear SVM", "NLI DistilBERT",
         "Dummy (majority)", "NLI BART", "NLI DeBERTa", "Dummy (stratified)"]
PRED_COL = {"Rule-based": "rule_based_label", "Qwen2.5-72B": "llm_models_Qwen--Qwen2_5-72B-Instruct_label",
            "Yi-1.5-9B": "llm_models_01-ai--Yi-1_5-9B-Chat_label",
            "Mistral-7B": "llm_models_mistralai--Mistral-7B-Instruct-v0_3_label",
            "Phi-4-mini": "llm_models_microsoft--Phi-4-mini-instruct_label",
            "Llama-3.1-8B": "llm_models_meta-llama--Llama-3_1-8B-Instruct_label", "qwen-7b": "llm_models_qwen-7b_label",
            "Qwen2.5-7B": "llm_models_Qwen--Qwen2_5-7B-Instruct_label",
            "Random Forest": "supervised_RandomForest_label", "XGBoost": "supervised_XGBoost_label",
            "LightGBM": "supervised_LightGBM_label", "Logistic Regression": "supervised_LogisticRegression_label",
            "Linear SVM": "supervised_LinearSVM_label", "NLI BART": "nli_bart_label",
            "NLI DeBERTa": "nli_deberta_label", "NLI DistilBERT": "nli_distilbert_label",
            "Dummy (majority)": "supervised_Dummy_majority_label",
            "Dummy (stratified)": "supervised_Dummy_stratified_label"}


def f3(x: float) -> str:
    return f"{x:.3f}".replace("-", "$-$")


def ci(lo: float, hi: float) -> str:
    fmt = lambda v: f"{0.0 if round(v, 2) == 0 else v:.2f}"  # noqa: E731  (avoid "-0.00")
    return f"[{fmt(lo)}, {fmt(hi)}]".replace("-", "$-$")


def write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text(f"% generated by revision/manuscript/build_tables.py; do not edit by hand\n{body}\n",
                                     encoding="utf-8")


def consensus_table(T: pd.DataFrame) -> None:
    rows = []
    for s in ORDER:
        r = T.loc[s]
        rows.append(f"{s} & {r['family']} & {f3(r['accuracy__consensus'])} {ci(r['accuracy__channel_id_lo'], r['accuracy__channel_id_hi'])}"
                    f" & {f3(r['accuracy__consensus'] - 48 / 69)} {ci(r['acc_minus_majority__channel_id_lo'], r['acc_minus_majority__channel_id_hi'])}"
                    f" & {f3(r['kappa__consensus'])} {ci(r['kappa__channel_id_lo'], r['kappa__channel_id_hi'])}"
                    f" & {f3(r['ac1__consensus'])} {ci(r['ac1__channel_id_lo'], r['ac1__channel_id_hi'])}"
                    f" & {f3(r['macro_f1__consensus'])} {ci(r['macro_f1__channel_id_lo'], r['macro_f1__channel_id_hi'])} \\\\")
    write("tab_consensus", "\n".join(rows))


def perrater_table(T: pd.DataFrame) -> None:
    rows = []
    for s in ORDER:
        r = T.loc[s]
        rows.append(f"{s} & {f3(r['kappa__rater1'])} {ci(r['kappa_r1__channel_id_lo'], r['kappa_r1__channel_id_hi'])}"
                    f" & {f3(r['kappa__rater2'])} {ci(r['kappa_r2__channel_id_lo'], r['kappa_r2__channel_id_hi'])}"
                    f" & {f3(r['ac1__rater1'])} {ci(r['ac1_r1__channel_id_lo'], r['ac1_r1__channel_id_hi'])}"
                    f" & {f3(r['ac1__rater2'])} {ci(r['ac1_r2__channel_id_lo'], r['ac1_r2__channel_id_hi'])} \\\\")
    write("tab_perrater", "\n".join(rows))


def mcnemar_table() -> None:
    M = pd.read_csv(REV / "statistics" / "mcnemar_rule_vs_17.csv")
    cols = M.columns
    def pick(*names):
        for n in names:
            if n in cols:
                return n
        raise KeyError(names)
    c_other = pick("other", "system", "other_system")
    c_b = pick("rule_right_other_wrong", "rule_correct_other_wrong")
    c_c = pick("rule_wrong_other_right", "rule_wrong_other_correct")
    c_p = pick("p_exact", "p")
    c_h = pick("p_holm", "p_holm_17")
    c_d = pick("acc_diff", "accuracy_difference")
    c_lo = pick("acc_diff_lo_channel")
    c_hi = pick("acc_diff_hi_channel")
    M = M.set_index(c_other).loc[[s for s in ORDER if s != "Rule-based"]]
    fp = lambda p: "$<$0.001" if p < 0.001 else f"{p:.3f}"  # noqa: E731
    rows = [f"{s} & {int(r[c_b])} & {int(r[c_c])} & {fp(r[c_p])} & {fp(r[c_h])} & {f3(r[c_d])} {ci(r[c_lo], r[c_hi])} \\\\"
            for s, r in M.iterrows()]
    write("tab_mcnemar", "\n".join(rows))


def disagreement_table(P: pd.DataFrame, A: pd.DataFrame) -> dict:
    dis = P[P["rater1_3class"] != P["rater2_3class"]]
    varied = set(A.loc[A["varied"], "system"])
    fam = dict(zip(A["system"], A["family"]))
    groups = {"Rule-based": ["Rule-based"],
              "LLMs (7)": [s for s in ORDER if fam[s] == "LLM"],
              "Supervised ML (5)": [s for s in ORDER if fam[s] == "Supervised"],
              "Dummy (stratified)": ["Dummy (stratified)"]}
    rows, tot = [], np.zeros(3, int)
    for g, systems in groups.items():
        systems = [s for s in systems if s in varied]
        c = np.zeros(3, int)
        for s in systems:
            p = dis[PRED_COL[s]]
            c += [int(np.sum(p == dis["rater1_3class"])), int(np.sum(p == dis["rater2_3class"])),
                  int(np.sum((p != dis["rater1_3class"]) & (p != dis["rater2_3class"])))]
        tot += c
        n = c.sum()
        rows.append(f"{g} & {n} & {c[0]} ({100 * c[0] / n:.1f}\\%) & {c[1]} ({100 * c[1] / n:.1f}\\%) & {c[2]} ({100 * c[2] / n:.1f}\\%) \\\\")
    n = tot.sum()
    rows.append("\\midrule")
    rows.append(f"All varied systems & {n} & {tot[0]} ({100 * tot[0] / n:.1f}\\%) & {tot[1]} ({100 * tot[1] / n:.1f}\\%) & {tot[2]} ({100 * tot[2] / n:.1f}\\%) \\\\")
    write("tab_disagreement", "\n".join(rows))
    allc = np.zeros(3, int)
    for s in ORDER:
        p = dis[PRED_COL[s]]
        allc += [int(np.sum(p == dis["rater1_3class"])), int(np.sum(p == dis["rater2_3class"])),
                 int(np.sum((p != dis["rater1_3class"]) & (p != dis["rater2_3class"])))]
    return {"n_dis": len(dis), "all18": allc.tolist(), "varied": tot.tolist(), "n_varied": len(varied)}


def gate_table(P: pd.DataFrame) -> dict:
    prompts = json.loads((REV / "prompt_ablation" / "outputs" / "prompts_by_condition.json").read_text(encoding="utf-8"))
    F = pd.DataFrame({cid: json.loads(re.search(r"Features:\s*(\{.+\})", t, re.S).group(1))
                      for cid, t in prompts["C0"].items()}).T
    H = pd.read_csv(CODE / "output" / "3class_eval" / "phase_a" / "hrsf" / "hrsf_predictions_at_best_alpha.csv").set_index("child_id")
    man = pd.read_csv(REV / "label_audit" / "sample_manifest.csv").set_index("sequence_id")
    fires = (F["visible_ratio"].astype(float) < 0.50) | (F["max_occlusion_streak"].astype(float) > 30) | \
            (F["eyes_closed_ratio"].astype(float) > 0.30)
    flagged = F.index[fires]
    assert len(flagged) == 7 and all(H.loc[flagged, "hrsf_alpha_0.60"] == "others")
    rows = []
    for cid in sorted(flagged):
        f, h = F.loc[cid], H.loc[cid]
        short = cid.replace(":person_", "/p")
        rows.append(f"\\texttt{{{short.replace('_', chr(92) + '_')}}} & {float(f['visible_ratio']):.2f} & "
                    f"{int(f['max_occlusion_streak'])} & {float(f['eyes_closed_ratio']):.2f} & {int(man.loc[cid, 'fps'])} & "
                    f"{h['rater1']} & {h['rater2']} & {h['consensus']} & {h['rule']} \\\\")
    write("tab_gate_flags", "\n".join(rows))
    rule_correct = int(np.sum(H.loc[flagged, "rule"] == H.loc[flagged, "consensus"]))
    tp = int(np.sum(H.loc[flagged, "consensus"] == "others"))
    return {"flagged": len(flagged), "rule_correct_on_flagged": rule_correct, "tp": tp}


def supervised_table() -> None:
    S = pd.read_csv(REV / "supervised_grouped" / "supervised_grouped_metrics.csv")
    scheme_col = [c for c in S.columns if "scheme" in c or c == "cv"][0]
    model_col = [c for c in S.columns if c in ("model", "system")][0]
    kcol = [c for c in S.columns if c in ("kappa", "kappa_consensus", "cohen_kappa")][0]
    names = {"RandomForest": "Random Forest", "XGBoost": "XGBoost", "LightGBM": "LightGBM",
             "LogisticRegression": "Logistic Regression", "LinearSVM": "Linear SVM",
             "Dummy_majority": "Dummy (majority)", "Dummy_stratified": "Dummy (stratified)"}
    T = pd.read_csv(REV / "statistics" / "system_metrics_with_cis.csv").set_index("system")
    schemes = sorted(S[scheme_col].unique())
    def find(sub):
        return [s for s in schemes if sub in s.lower()][0]
    loco, lovo = find("channel"), find("video")
    rows = []
    for m, nice in names.items():
        k = S[S[model_col] == m].set_index(scheme_col)[kcol]
        orig = T.loc[nice, "kappa__consensus"]
        rows.append(f"{nice} & {f3(orig)} & {f3(k[loco])} & {f3(k[lovo])} \\\\")
    write("tab_supervised_cv", "\n".join(rows))


def prompt_table() -> None:
    D = pd.read_csv(REV / "prompt_ablation" / "ablation_metrics_full_precision.csv")
    piv = D.pivot(index="model", columns="condition", values="kappa_consensus")
    nice = {"Qwen2.5-72B-Instruct": "Qwen2.5-72B", "Yi-1.5-9B-Chat": "Yi-1.5-9B", "Mistral-7B-Instruct-v0.3": "Mistral-7B",
            "Phi-4-mini-instruct": "Phi-4-mini", "Llama-3.1-8B-Instruct": "Llama-3.1-8B", "qwen-7b": "qwen-7b",
            "Qwen2.5-7B-Instruct": "Qwen2.5-7B"}
    rows = [f"{n} & " + " & ".join(f3(piv.loc[m, c]) for c in ["C0", "C1", "C2", "C3", "C4"]) + " \\\\"
            for m, n in nice.items()]
    write("tab_prompt_ablation", "\n".join(rows))


def crosstab_table(P: pd.DataFrame) -> None:
    ct = pd.crosstab(P["rater1_3class"], P["rater2_3class"]).reindex(index=LABELS, columns=LABELS, fill_value=0)
    rows = [f"Rater 1: {a} & " + " & ".join(str(int(ct.loc[a, b])) for b in LABELS) + f" & {int(ct.loc[a].sum())} \\\\"
            for a in LABELS]
    rows.append("\\midrule")
    rows.append("Total & " + " & ".join(str(int(ct[b].sum())) for b in LABELS) + f" & {int(ct.values.sum())} \\\\")
    write("tab_crosstab", "\n".join(rows))


def supplementary(P: pd.DataFrame) -> None:
    SUPP.mkdir(parents=True, exist_ok=True)
    man = pd.read_csv(REV / "label_audit" / "sample_manifest.csv")
    man[["sequence_id", "clip_id", "video_id", "channel_id", "fps", "observed_frames", "rater1", "rater2",
         "consensus", "resolution"]].to_csv(SUPP / "S1_sequence_labels.csv", index=False)
    pd.read_csv(REV / "label_audit" / "disagreement_cases.csv").to_csv(SUPP / "S2_disagreement_sequences_features.csv",
                                                                      index=False)
    pd.read_csv(REV / "statistics" / "system_metrics_with_cis.csv").to_csv(SUPP / "S3_system_metrics_with_cis.csv",
                                                                         index=False)
    pd.read_csv(REV / "statistics" / "mcnemar_all_153_pairs.csv").to_csv(SUPP / "S4_mcnemar_all_153_pairs.csv",
                                                                       index=False)
    pd.read_csv(REV / "prompt_ablation" / "ablation_metrics_full_precision.csv").to_csv(
        SUPP / "S5_prompt_ablation_metrics.csv", index=False)
    pd.read_csv(REV / "nli_sensitivity" / "nli_sensitivity_metrics.csv").to_csv(SUPP / "S6_nli_sensitivity_metrics.csv",
                                                                               index=False)
    prompts = json.loads((REV / "prompt_ablation" / "outputs" / "prompts_by_condition.json").read_text(encoding="utf-8"))
    fewshot = REV / "prompt_ablation" / "outputs" / "prompts_fewshot.json"
    if fewshot.exists():
        prompts.update(json.loads(fewshot.read_text(encoding="utf-8")))
    (SUPP / "S7_prompts_all_conditions.json").write_text(json.dumps(prompts, indent=1, ensure_ascii=True), encoding="utf-8")
    r3 = REV / "r3_analyses"
    if (r3 / "llm_calibration.csv").exists():
        pd.read_csv(r3 / "llm_calibration.csv").to_csv(SUPP / "S8_llm_calibration.csv", index=False)
        pd.read_csv(r3 / "case_studies.csv").to_csv(SUPP / "S9_case_studies.csv", index=False)
        (SUPP / "S9_case_studies_llm_explanations.json").write_text(
            (r3 / "case_studies_llm_explanations.json").read_text(encoding="utf-8"), encoding="utf-8")
    pd.read_csv(CODE / "output" / "3class_eval" / "phase_a" / "feature_importance_3class.csv").to_csv(
        SUPP / "S10_random_forest_feature_importance.csv", index=False)
    fs = REV / "prompt_ablation" / "fewshot_metrics.csv"
    if fs.exists():
        pd.read_csv(fs).to_csv(SUPP / "S11_fewshot_metrics.csv", index=False)


def main() -> None:
    T = pd.read_csv(REV / "statistics" / "system_metrics_with_cis.csv").set_index("system")
    A = pd.read_csv(REV / "statistics" / "alignment_delta.csv")
    P = pd.read_csv(CODE / "output" / "all_predictions_3class.csv")
    consensus_table(T)
    perrater_table(T)
    mcnemar_table()
    info = disagreement_table(P, A)
    info.update(gate_table(P))
    supervised_table()
    prompt_table()
    crosstab_table(P)
    supplementary(P)
    print(json.dumps(info))
    print("tables:", sorted(p.name for p in OUT.glob("*.tex")))


if __name__ == "__main__":
    main()
