"""Sensitivity of the rule-based classifier to the stability-score weights
(Reviewer 4, minor comment 6: "explain why the stability score uses the
weights 0.45, 0.25, 0.15, 0.15").

attention_stability_score = clip(w1*visible_ratio + w2*max_visible_streak/N
                                 + w3*(1 - min(mean_gaze_motion/300, 1))
                                 + w4*(1 - gaze_shift_ratio), 0, 1)

The rule uses it only in the `focused` test (score >= 0.65, unchanged here).
Weight sets are fixed in advance: equal weights, each component dropped with
the rest renormalised, and every +/-0.05 shift of weight between two
components. Writes STABILITY_WEIGHTS.md. numpy and pandas only.
"""

from __future__ import annotations

import itertools
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CODE = ROOT / "code" if (ROOT / "code" / "output").is_dir() else ROOT  # project layout or repository layout
EVAL = CODE / "output" / "3class_eval"
PAPER = (0.45, 0.25, 0.15, 0.15)
NAMES = ("visibility", "longest visible streak", "low gaze motion", "few gaze shifts")


def load():
    pattern = re.compile(r"Features:\s*(\{.+\})", re.DOTALL)
    rows = []
    with (EVAL / "llm_models_Qwen--Qwen2_5-72B-Instruct_prompts.jsonl").open(encoding="utf-8") as fh:
        for line in fh:
            rec = json.loads(line)
            f = json.loads(pattern.search(rec["prompt"]).group(1))
            f["child_id"] = rec["child_id"]
            rows.append(f)
    f = pd.DataFrame(rows).set_index("child_id")
    gt = pd.read_csv(EVAL / "ground_truth_3class.csv").set_index("child_id")
    return f.reindex(gt.index), gt


def components(f):
    return np.stack([f["visible_ratio"].to_numpy(),
                     (f["max_visible_streak"] / f["observed_frames"]).to_numpy(),
                     1 - np.minimum(f["mean_gaze_motion"].to_numpy() / 300.0, 1.0),
                     1 - f["gaze_shift_ratio"].to_numpy()], axis=1)


def rule(f, stab):
    others = (f["eyes_closed_ratio"] >= 0.3) | (f["occlusion_ratio"] >= 0.35)
    focused = ((f["visible_ratio"] >= 0.75) & (f["gaze_shift_ratio"] <= 0.1)
               & (f["mean_gaze_motion"] <= 120) & (stab >= 0.65))
    return np.where(others, "others", np.where(focused, "focused", "mix"))


def kappa(a, b):
    po = np.mean(a == b)
    pe = sum(np.mean(a == c) * np.mean(b == c) for c in ("focused", "mix", "others"))
    return (po - pe) / (1 - pe)


def main() -> None:
    f, gt = load()
    C = components(f)
    y = gt["final_3class"].to_numpy()
    stored = f["attention_stability_score"].to_numpy()
    paper_stab = np.clip(C @ np.array(PAPER), 0, 1)
    assert np.allclose(paper_stab, stored, atol=1e-9), "stability formula does not reproduce stored scores"
    base = rule(f, paper_stab)

    sets = {"paper (0.45, 0.25, 0.15, 0.15)": PAPER, "equal (0.25 each)": (0.25,) * 4}
    for i, n in enumerate(NAMES):
        w = np.array(PAPER, dtype=float); w[i] = 0; w /= w.sum()
        sets[f"drop {n}"] = tuple(w)
    for i, j in itertools.permutations(range(4), 2):
        w = np.array(PAPER, dtype=float); w[i] += 0.05; w[j] -= 0.05
        sets[f"+0.05 {NAMES[i]}, -0.05 {NAMES[j]}"] = tuple(w)

    rows = []
    for name, w in sets.items():
        p = rule(f, np.clip(C @ np.array(w), 0, 1))
        rows.append({"weights": name, "w": ", ".join(f"{x:.3f}" for x in w), "kappa": kappa(p, y),
                     "accuracy": float(np.mean(p == y)), "changed_vs_paper": int(np.sum(p != base))})
    R = pd.DataFrame(rows)
    R.to_csv(HERE / "stability_weights_sensitivity.csv", index=False)
    pert = R.iloc[6:]
    L = ["# Stability-score weight sensitivity", "",
         "Generated by `stability_weights_sensitivity.py`. The stored scores are reproduced exactly by the formula. "
         "Rule thresholds unchanged; only the weights vary.", "",
         f"- Across all {len(R)} weight sets, rule κ ranges from **{R['kappa'].min():.3f} to {R['kappa'].max():.3f}** "
         f"(paper weights: {R.iloc[0]['kappa']:.3f}).",
         f"- Over the {len(pert)} ±0.05 shifts, at most {pert['changed_vs_paper'].max()} of 69 predictions change "
         f"(κ {pert['kappa'].min():.3f} to {pert['kappa'].max():.3f}).", "",
         "| Weight set | Weights (vis, streak, motion, shift) | κ | Accuracy | Predictions changed |", "|---|---|---|---|---|"]
    L += [f"| {r['weights']} | {r['w']} | {r['kappa']:.3f} | {r['accuracy']:.3f} | {r['changed_vs_paper']} |" for _, r in R.iterrows()]
    (HERE / "STABILITY_WEIGHTS.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L[:7]))


if __name__ == "__main__":
    main()
