"""Details behind the prompt-ablation tables (server run, paper's precision).

1. Change in kappa from C0 to each other condition, per model, with a 95%
   paired cluster-bootstrap CI (YouTube channels, 5000 replicates, as in
   revision/statistics/recompute_stats.py).
2. Where the `others` predictions fall in each condition: sequence,
   dominant_gaze_class and consensus label; and the rule's own `others`.
3. The Phi-4-mini C0 raw-text difference against the original outputs.
4. Precision sensitivity: C0 labels of the local 4-bit run against the
   server run.

Writes ABLATION_DETAILS_FULL_PRECISION.md. numpy and pandas only.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE))
from evaluate_ablation import CONDITIONS, EVAL, LABELS, ORIGINAL, OUT, kappa, parse, rule  # noqa: E402

SERVER = HERE / "outputs_full_precision"
N_BOOT = 5000
SEED = 20261005


def load_preds(run_dir: Path, name: str, cond: str) -> pd.Series | None:
    path = run_dir / f"{name}__{cond}.jsonl"
    if not path.exists():
        return None
    recs = [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]
    return pd.Series({r["child_id"]: parse(r["raw"])[0] for r in recs})


def main() -> None:
    gt = pd.read_csv(EVAL / "ground_truth_3class.csv").set_index("child_id")
    man = pd.read_csv(ROOT / "revision" / "label_audit" / "sample_manifest.csv").set_index("sequence_id")
    ids = list(gt.index)
    y = gt["final_3class"].to_numpy()
    prompts = json.loads((OUT / "prompts_by_condition.json").read_text(encoding="utf-8"))
    feats = {cid: json.loads(re.search(r"Features:\s*(\{.+\})", t, re.S).group(1)) for cid, t in prompts["C0"].items()}
    dom = pd.Series({cid: f.get("dominant_gaze_class") for cid, f in feats.items()})
    rule_pred = pd.Series({cid: rule(f) for cid, f in feats.items()})

    rng = np.random.default_rng(SEED)
    ch = man.loc[ids, "channel_id"].to_numpy()
    groups = [np.flatnonzero(ch == g) for g in pd.unique(ch)]
    boots = [np.concatenate([groups[i] for i in rng.integers(0, len(groups), len(groups))]) for _ in range(N_BOOT)]

    P = {(m, c): load_preds(SERVER, m, c) for m in ORIGINAL for c in CONDITIONS}
    L = ["# Prompt ablation: details (server run, paper's precision)", "",
         f"Generated by `ablation_details.py`. Paired cluster bootstrap over {len(groups)} YouTube channels, "
         f"{N_BOOT} replicates, seed {SEED}.", "",
         "## Change in kappa against C0 (95% CI)", "",
         "| Model | C1 − C0 | C2 − C0 | C3 − C0 | C4 − C0 |", "|---|---|---|---|---|"]
    for m in ORIGINAL:
        a = P[(m, "C0")].loc[ids].to_numpy()
        cells = []
        for c in CONDITIONS[1:]:
            b = P[(m, c)].loc[ids].to_numpy()
            d = kappa(b, y) - kappa(a, y)
            reps = np.array([kappa(b[i], y[i]) - kappa(a[i], y[i]) for i in boots])
            reps = reps[~np.isnan(reps)]
            lo, hi = np.percentile(reps, [2.5, 97.5])
            cells.append(f"{d:+.3f} [{lo:+.3f}, {hi:+.3f}]" + (" *" if lo > 0 or hi < 0 else ""))
        L.append(f"| {m} | " + " | ".join(cells) + " |")
    L += ["", "`*` = CI excludes zero.", ""]

    L += ["## Where the `others` predictions fall", "",
          "| Condition | Model | Sequence | dominant_gaze_class | Consensus | Rule |", "|---|---|---|---|---|---|"]
    for c in CONDITIONS:
        for m in ORIGINAL:
            p = P[(m, c)]
            for cid in p.index[p == "others"]:
                L.append(f"| {c} | {m} | {cid} | {dom[cid]} | {gt.loc[cid, 'final_3class']} | {rule_pred[cid]} |")
    true_others = list(gt.index[gt["final_3class"] == "others"])
    outside = [f"{c} ({gt.loc[c, 'final_3class']})" for c in dom.index[dom == "outside_frame"]]
    L += ["", f"Consensus `others` sequences: {', '.join(true_others)} "
          f"(dominant_gaze_class: {', '.join(str(dom[c]) for c in true_others)}; rule: "
          f"{', '.join(rule_pred[c] for c in true_others)}).",
          f"Rule `others` predictions: {', '.join(rule_pred.index[rule_pred == 'others']) or 'none'}.",
          f"Sequences with dominant_gaze_class = outside_frame: {', '.join(outside)}.", ""]

    orig = {json.loads(l)["child_id"]: json.loads(l)["raw"] for l in
            (EVAL / f"llm_models_{ORIGINAL['Phi-4-mini-instruct']}_raw.jsonl").read_text(encoding="utf-8").splitlines()
            if l.strip()}
    new = {json.loads(l)["child_id"]: json.loads(l)["raw"] for l in
           (SERVER / "Phi-4-mini-instruct__C0.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()}
    prefix = sum(orig[c].strip().startswith(new[c].strip()) for c in new)
    extra = [len(orig[c].strip()) - len(new[c].strip()) for c in new]
    L += ["## Phi-4-mini C0 raw text against the original", "",
          f"Re-run text is a prefix of the original text for {prefix} of {len(new)} sequences; the original runs "
          f"continue for {min(extra)}–{max(extra)} more characters (median {int(np.median(extra))}) after the answer. "
          "The re-run stops at the model's end token, so only text after the answer differs; labels are identical.", ""]

    L += ["## Precision sensitivity: local 4-bit C0 against server C0", "",
          "| Model | Same label (of 69) | kappa 4-bit | kappa server |", "|---|---|---|---|"]
    for m in ORIGINAL:
        loc = load_preds(OUT, m, "C0")
        if loc is None:
            L.append(f"| {m} | not run locally | — | {kappa(P[(m, 'C0')].loc[ids].to_numpy(), y):.3f} |")
            continue
        s = P[(m, "C0")].loc[ids].to_numpy()
        l4 = loc.loc[ids].to_numpy()
        L.append(f"| {m} | {int(np.sum(s == l4))} | {kappa(l4, y):.3f} | {kappa(s, y):.3f} |")
    (HERE / "ABLATION_DETAILS_FULL_PRECISION.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
