"""Score the out-of-fold few-shot runs (FS3_s1-3) against the zero-shot original (C0).

Per model and example draw: kappa against the consensus, the change from C0
with a 95% paired cluster-bootstrap interval over channels (5000 replicates,
seed 20261005), and the `others` predictions (how many, how many correct).
Writes FEWSHOT_RESULTS.md, fewshot_metrics.csv and revision/overleaf/tables/tab_fewshot.tex.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REV = HERE.parent
sys.path.insert(0, str(HERE))
from evaluate_ablation import EVAL, ORIGINAL, kappa, parse  # noqa: E402

RUN = HERE / "outputs_full_precision"
SEEDS = ["FS3_s1", "FS3_s2", "FS3_s3"]
NICE = {"Qwen2.5-72B-Instruct": "Qwen2.5-72B", "Yi-1.5-9B-Chat": "Yi-1.5-9B", "Mistral-7B-Instruct-v0.3": "Mistral-7B",
        "Phi-4-mini-instruct": "Phi-4-mini", "Llama-3.1-8B-Instruct": "Llama-3.1-8B", "qwen-7b": "qwen-7b",
        "Qwen2.5-7B-Instruct": "Qwen2.5-7B"}


def load(name: str, cond: str) -> tuple[pd.Series, int]:
    recs = [json.loads(l) for l in (RUN / f"{name}__{cond}.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    parsed = {r["child_id"]: parse(r["raw"]) for r in recs}
    return pd.Series({c: v[0] for c, v in parsed.items()}), sum(v[1] != "ok" for v in parsed.values())


def main() -> None:
    gt = pd.read_csv(EVAL / "ground_truth_3class.csv").set_index("child_id")
    man = pd.read_csv(REV / "label_audit" / "sample_manifest.csv").set_index("sequence_id")
    ids = list(gt.index)
    y = gt["final_3class"].to_numpy()
    rng = np.random.default_rng(20261005)
    ch = man.loc[ids, "channel_id"].to_numpy()
    groups = [np.flatnonzero(ch == g) for g in pd.unique(ch)]
    boots = [np.concatenate([groups[i] for i in rng.integers(0, len(groups), len(groups))]) for _ in range(5000)]
    rows = []
    for name in ORIGINAL:
        c0, _ = load(name, "C0")
        a = c0.loc[ids].to_numpy()
        k0 = kappa(a, y)
        for cond in SEEDS:
            p, bad = load(name, cond)
            b = p.loc[ids].to_numpy()
            reps = np.array([kappa(b[i], y[i]) - kappa(a[i], y[i]) for i in boots])
            reps = reps[~np.isnan(reps)]
            lo, hi = np.percentile(reps, [2.5, 97.5])
            rows.append({"model": NICE[name], "draw": cond, "kappa_c0": k0, "kappa_fewshot": kappa(b, y),
                         "delta": kappa(b, y) - k0, "delta_lo": lo, "delta_hi": hi, "accuracy": float(np.mean(b == y)),
                         "pred_others": int(np.sum(b == "others")), "correct_others": int(np.sum((b == "others") & (y == "others"))),
                         "unparsed": bad})
    D = pd.DataFrame(rows)
    D.to_csv(HERE / "fewshot_metrics.csv", index=False)
    lines, md = [], ["# Out-of-fold few-shot results", "", "| Model | C0 κ | FS3 κ (draws 1/2/3) | mean | Δκ [95% CI] per draw | others predicted (correct) |",
                     "|---|---|---|---|---|---|"]
    f3 = lambda x: f"{x:.3f}".replace("-", "$-$")  # noqa: E731
    order = ["Qwen2.5-72B", "Yi-1.5-9B", "Mistral-7B", "Phi-4-mini", "Llama-3.1-8B", "qwen-7b", "Qwen2.5-7B"]
    for m in order:
        g = D[D["model"] == m]
        ks = g["kappa_fewshot"].to_numpy()
        ex = sum((g["delta_lo"] > 0) | (g["delta_hi"] < 0))
        oth = "/".join(f"{r.pred_others} ({r.correct_others})" for r in g.itertuples())
        lines.append(f"{m} & {f3(g['kappa_c0'].iloc[0])} & {f3(ks[0])} & {f3(ks[1])} & {f3(ks[2])} & {f3(ks.mean())} & "
                     f"{f3(g['delta'].mean())} & {ex} \\\\")
        md.append(f"| {m} | {g['kappa_c0'].iloc[0]:.3f} | {' / '.join(f'{k:.3f}' for k in ks)} | {ks.mean():.3f} | "
                  + "; ".join(f"{r.delta:+.3f} [{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]" for r in g.itertuples())
                  + f" | {oth} |")
    (REV / "overleaf" / "tables").mkdir(parents=True, exist_ok=True)
    (REV / "overleaf" / "tables" / "tab_fewshot.tex").write_text(
        "% generated by revision/prompt_ablation/evaluate_fewshot.py\n" + "\n".join(lines) + "\n", encoding="utf-8")
    md += ["", f"Unparsed outputs: {int(D['unparsed'].sum())} of {len(D) * 69}."]
    (HERE / "FEWSHOT_RESULTS.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(md))


if __name__ == "__main__":
    main()
