"""Analyses added for Reviewer 3 (points 2, 4, 5 and 6). All on existing outputs; no new model runs.

1. Calibration of the LLMs' stated confidence (original C0 outputs): accuracy,
   mean confidence, expected calibration error (10 equal-width bins), and the
   AUROC of confidence for separating correct from wrong predictions.
2. Case studies: the three consensus `others` sequences and the two
   `outside_frame` sequences, with key features, every system's prediction and
   the LLMs' own short explanations.
3. Inter-rater disagreements: which class pairs, and the features of the
   disagreement sequences compared with the agreed ones.

Writes R3_ANALYSES.md and CSVs here, and LaTeX rows to revision/overleaf/tables/.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REV = HERE.parent
ROOT = REV.parent
CODE = ROOT / "code" if (ROOT / "code" / "output").is_dir() else ROOT  # project layout or repository layout
EVAL = CODE / "output" / "3class_eval"
TABLES = REV / "overleaf" / "tables"
LLMS = {"Qwen2.5-72B": "Qwen--Qwen2_5-72B-Instruct", "Yi-1.5-9B": "01-ai--Yi-1_5-9B-Chat",
        "Mistral-7B": "mistralai--Mistral-7B-Instruct-v0_3", "Phi-4-mini": "microsoft--Phi-4-mini-instruct",
        "Llama-3.1-8B": "meta-llama--Llama-3_1-8B-Instruct", "qwen-7b": "qwen-7b",
        "Qwen2.5-7B": "Qwen--Qwen2_5-7B-Instruct"}
SUP = {"Random Forest": "supervised_RandomForest_label", "XGBoost": "supervised_XGBoost_label",
       "LightGBM": "supervised_LightGBM_label", "Logistic Regression": "supervised_LogisticRegression_label",
       "Linear SVM": "supervised_LinearSVM_label"}


def ece(conf: np.ndarray, correct: np.ndarray, bins: int = 10) -> float:
    edges = np.linspace(0, 1, bins + 1)
    idx = np.clip(np.digitize(conf, edges[1:-1], right=True), 0, bins - 1)
    return float(sum(abs(correct[idx == b].mean() - conf[idx == b].mean()) * np.mean(idx == b)
                     for b in range(bins) if np.any(idx == b)))


def auroc(score: np.ndarray, positive: np.ndarray) -> float:
    pos, neg = score[positive], score[~positive]
    if len(pos) == 0 or len(neg) == 0:
        return float("nan")
    greater = (pos[:, None] > neg[None, :]).sum() + 0.5 * (pos[:, None] == neg[None, :]).sum()
    return float(greater / (len(pos) * len(neg)))


def f3(x: float) -> str:
    return "--" if pd.isna(x) else f"{x:.3f}".replace("-", "$-$")


def calibration() -> pd.DataFrame:
    rows = []
    for name, d in LLMS.items():
        df = pd.read_csv(EVAL / f"llm_models_{d}_3class.csv")
        conf = df["confidence"].astype(float).to_numpy()
        corr = df["correct"].astype(str).str.lower().eq("true").to_numpy()
        rows.append({"model": name, "accuracy": corr.mean(), "mean_confidence": conf.mean(),
                     "mean_conf_correct": conf[corr].mean(), "mean_conf_wrong": conf[~corr].mean(),
                     "ece_10bins": ece(conf, corr), "auroc_conf_correct": auroc(conf, corr),
                     "distinct_confidence_values": len(np.unique(conf))})
    C = pd.DataFrame(rows)
    C.to_csv(HERE / "llm_calibration.csv", index=False)
    TABLES.mkdir(parents=True, exist_ok=True)
    lines = [f"{r.model} & {f3(r.accuracy)} & {f3(r.mean_confidence)} & {f3(r.mean_conf_correct)} & "
             f"{f3(r.mean_conf_wrong)} & {f3(r.ece_10bins)} & {f3(r.auroc_conf_correct)} \\\\" for r in C.itertuples()]
    (TABLES / "tab_calibration.tex").write_text("% generated by revision/r3_analyses/r3_analyses.py\n" + "\n".join(lines) + "\n",
                                                encoding="utf-8")
    return C


def case_studies() -> tuple[pd.DataFrame, dict]:
    P = pd.read_csv(CODE / "output" / "all_predictions_3class.csv").set_index("child_id")
    prompts = json.loads((REV / "prompt_ablation" / "outputs" / "prompts_by_condition.json").read_text(encoding="utf-8"))
    F = {cid: json.loads(re.search(r"Features:\s*(\{.+\})", t, re.S).group(1)) for cid, t in prompts["C0"].items()}
    gate = {cid: (f["visible_ratio"] < 0.5) or (f["max_occlusion_streak"] > 30) or (f["eyes_closed_ratio"] > 0.3)
            for cid, f in F.items()}
    llm = {n: pd.read_csv(EVAL / f"llm_models_{d}_3class.csv").set_index("child_id") for n, d in LLMS.items()}
    others = list(P.index[P["final_manual_label_3class"] == "others"])
    outside = [c for c, f in F.items() if f["dominant_gaze_class"] == "outside_frame"]
    cases = others + [c for c in outside if c not in others]
    rows, expl = [], {}
    for cid in cases:
        f = F[cid]
        votes = pd.Series([llm[n].loc[cid, "pred_3class"] for n in LLMS]).value_counts()
        sup = pd.Series([P.loc[cid, c] for c in SUP.values()]).value_counts()
        rows.append({"sequence": cid, "visible_ratio": f["visible_ratio"], "occlusion_ratio": f["occlusion_ratio"],
                     "eyes_closed_ratio": f["eyes_closed_ratio"], "max_occlusion_streak": f["max_occlusion_streak"],
                     "observed_frames": f["observed_frames"], "dominant_gaze_class": f["dominant_gaze_class"],
                     "rater1": P.loc[cid, "rater1_3class"], "rater2": P.loc[cid, "rater2_3class"],
                     "consensus": P.loc[cid, "final_manual_label_3class"], "rule": P.loc[cid, "rule_based_label"],
                     "gate_fires": gate[cid],
                     "llm_votes": ", ".join(f"{k} {v}" for k, v in votes.items()),
                     "supervised_votes": ", ".join(f"{k} {v}" for k, v in sup.items())})
        expl[cid] = {n: {"label": llm[n].loc[cid, "pred_3class"], "confidence": float(llm[n].loc[cid, "confidence"]),
                         "explanation": str(llm[n].loc[cid, "reasoning"])} for n in LLMS}
    D = pd.DataFrame(rows)
    D.to_csv(HERE / "case_studies.csv", index=False)
    (HERE / "case_studies_llm_explanations.json").write_text(json.dumps(expl, indent=1, ensure_ascii=False),
                                                             encoding="utf-8")
    ab = {"f": "focused", "m": "mix", "o": "others"}
    short = lambda s: {"focused": "f", "mix": "m", "others": "o"}[s]  # noqa: E731
    def votes(s: str) -> str:
        parts = dict(p.split(" ") for p in s.split(", "))
        return "/".join(str(parts.get(ab[k], 0)) for k in ("f", "m", "o"))
    lines = []
    for i, r in enumerate(D.itertuples(), 1):
        lines.append(f"S{i} & {r.visible_ratio:.2f} & {r.occlusion_ratio:.2f} & {r.eyes_closed_ratio:.2f} & "
                     f"\\texttt{{{r.dominant_gaze_class.replace('_', chr(92) + '_')}}} & "
                     f"{short(r.rater1)}/{short(r.rater2)}/{short(r.consensus)} & {short(r.rule)} & "
                     f"{'o' if r.gate_fires else '--'} & {votes(r.llm_votes)} & {votes(r.supervised_votes)} \\\\")
    (TABLES / "tab_cases.tex").write_text("% generated by revision/r3_analyses/r3_analyses.py\n" + "\n".join(lines) + "\n",
                                          encoding="utf-8")
    return D, expl


def disagreements() -> dict:
    man = pd.read_csv(REV / "label_audit" / "sample_manifest.csv").set_index("sequence_id")
    prompts = json.loads((REV / "prompt_ablation" / "outputs" / "prompts_by_condition.json").read_text(encoding="utf-8"))
    F = pd.DataFrame({cid: json.loads(re.search(r"Features:\s*(\{.+\})", t, re.S).group(1))
                      for cid, t in prompts["C0"].items()}).T
    dis = man["rater1"] != man["rater2"]
    pairs = (man[dis].apply(lambda r: " / ".join(sorted([r["rater1"], r["rater2"]])), axis=1).value_counts().to_dict())
    feats = ["visible_ratio", "gaze_shift_ratio", "occlusion_ratio", "attention_stability_score", "mean_gaze_motion"]
    med = {f: {"disagree": float(F.loc[dis[dis].index, f].astype(float).median()),
               "agree": float(F.loc[dis[~dis].index, f].astype(float).median())} for f in feats}
    return {"n_disagree": int(dis.sum()), "pairs": pairs, "medians": med}


def main() -> None:
    C = calibration()
    D, expl = case_studies()
    dz = disagreements()
    L = ["# Analyses for Reviewer 3", "", "Generated by `r3_analyses.py` from existing outputs (no new model runs).", "",
         "## 1. Calibration of the LLMs' stated confidence (original runs)", "",
         C.to_markdown(index=False, floatfmt=".3f"), "",
         "## 2. Case studies", "", D.to_markdown(index=False, floatfmt=".2f"), "",
         "LLM explanations: `case_studies_llm_explanations.json`.", "",
         "## 3. Inter-rater disagreements", "", f"- Disagreements: {dz['n_disagree']}; class pairs: {dz['pairs']}",
         "- Medians (disagreement vs agreement sequences):"]
    L += [f"  - {f}: {v['disagree']:.3f} vs {v['agree']:.3f}" for f, v in dz["medians"].items()]
    (HERE / "R3_ANALYSES.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    for cid, e in expl.items():
        print("\n###", cid)
        for n, v in e.items():
            print(f"  {n}: {v['label']} ({v['confidence']}) {v['explanation'][:170]}")


if __name__ == "__main__":
    main()
